env:
  browser: true
  es2021: true
extends:
  - google
  - plugin:@typescript-eslint/eslint-recommended
  - plugin:lit/recommended
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: 12
  sourceType: module
plugins:
  - prettier
  - '@typescript-eslint'
rules: {
  prettier/prettier: 'error'
}
